(() => {
  const key='flt-v35-fleet';
  let data={drivers:[],trucks:[],trailers:[],locks:[],audit:[]};
  try{data={...data,...JSON.parse(localStorage.getItem(key)||'{}')}}catch(error){}
  const nav=document.getElementById('nav');
  const loadNav=nav?.querySelector('[data-view="load"]');
  if(!nav||!loadNav||document.getElementById('fleet'))return;
  const navButton=document.createElement('button');
  navButton.dataset.view='fleet';
  navButton.innerHTML='<span class="nav-icon">▤</span><span class="nav-label">Drivers & Equipment</span>';
  nav.insertBefore(navButton,loadNav);
  const section=document.createElement('section');
  section.className='view';section.id='fleet';
  section.innerHTML=`
    <div class="hero"><div><div class="eyebrow" style="color:var(--lime)">V3.5 individual records</div><h2>Drivers, Trucks, Trailers & Trip Lock</h2><p class="subtle">Each driver and asset keeps its own qualification, ratings, and verification status.</p></div></div>
    <div class="grid three">
      <div class="panel"><div class="eyebrow">Driver record</div><h2>Add driver</h2><form id="fleet-driver-form" class="form-grid" style="margin-top:14px"><div class="field full"><label>Driver name or internal ID</label><input name="name" required></div><div class="field full"><label>Qualification</label><select name="qualification"><option>Non-CDL Driver</option><option>CDL Class A</option><option>CDL Class B</option><option>CDL Class C</option><option>Commercial Learner's Permit</option><option>Not Applicable — Non-Driving User</option></select></div><div class="field"><label>Operating area</label><select name="area"><option>Intrastate Only</option><option>Interstate</option></select></div><div class="field"><label>License state</label><input name="licenseState" maxlength="2" placeholder="NC"></div><div class="field"><label>License expiration</label><input name="expiration" type="date"></div><div class="field full"><label>Endorsements</label><input name="endorsements" placeholder="None, Hazmat, Tanker, Passenger, etc."></div><div class="field full"><label>Restrictions</label><input name="restrictions" placeholder="None or list restrictions"></div><div class="field"><label>Status</label><select name="status"><option value="planned">Planned</option><option value="active">Active / Verified</option></select></div><div class="form-actions field full"><button class="btn primary">Save driver</button></div></form></div>
      <div class="panel"><div class="eyebrow">Truck record</div><h2>Add truck</h2><form id="fleet-truck-form" class="form-grid" style="margin-top:14px"><div class="field"><label>Unit ID</label><input name="unit" required placeholder="Truck 01"></div><div class="field"><label>VIN</label><input name="vin"></div><div class="field"><label>GVWR (lb)</label><input name="gvwr" type="number" min="1" required></div><div class="field"><label>GCWR (lb)</label><input name="gcwr" type="number" min="1"></div><div class="field"><label>Empty weight (lb)</label><input name="emptyWeight" type="number" min="1"></div><div class="field"><label>Status</label><select name="status"><option value="planned">Planned</option><option value="active">Active / Verified</option></select></div><div class="form-actions field full"><button class="btn primary">Save truck</button></div></form></div>
      <div class="panel"><div class="eyebrow">Trailer record</div><h2>Add trailer</h2><form id="fleet-trailer-form" class="form-grid" style="margin-top:14px"><div class="field"><label>Unit ID</label><input name="unit" required placeholder="Trailer 01"></div><div class="field"><label>VIN</label><input name="vin"></div><div class="field full"><label>Configuration</label><select name="configuration"><option>Gooseneck trailer</option><option>Bumper-pull trailer</option><option>Auto-hauler trailer</option><option>Enclosed trailer</option><option>No trailer</option></select></div><div class="field"><label>GVWR (lb)</label><input name="gvwr" type="number" min="1"></div><div class="field"><label>Empty weight (lb)</label><input name="emptyWeight" type="number" min="1"></div><div class="field full"><label>Status</label><select name="status"><option value="planned">Planned</option><option value="active">Active / Verified</option></select></div><div class="form-actions field full"><button class="btn primary">Save trailer</button></div></form></div>
    </div>
    <div class="grid three" style="margin-top:14px"><div class="panel"><div class="section-head"><h2>Drivers</h2><span class="tag gray" id="fleet-driver-count">0</span></div><div id="fleet-driver-list"></div></div><div class="panel"><div class="section-head"><h2>Trucks</h2><span class="tag gray" id="fleet-truck-count">0</span></div><div id="fleet-truck-list"></div></div><div class="panel"><div class="section-head"><h2>Trailers</h2><span class="tag gray" id="fleet-trailer-count">0</span></div><div id="fleet-trailer-list"></div></div></div>
    <div class="panel" style="margin-top:14px"><div class="section-head"><div><div class="eyebrow">Dispatch control</div><h2>Driver–Truck–Trailer Trip Lock</h2><p class="subtle" style="margin-top:5px">Only active, verified records can be locked to a dispatched load.</p></div><span class="tag gray" id="fleet-lock-status">Not locked</span></div><form id="fleet-lock-form" class="form-grid"><div class="field"><label>Load</label><select id="fleet-lock-load" required></select></div><div class="field"><label>Driver</label><select id="fleet-lock-driver" required></select></div><div class="field"><label>Truck</label><select id="fleet-lock-truck" required></select></div><div class="field"><label>Trailer</label><select id="fleet-lock-trailer" required></select></div><div class="field full"><label>Assignment reason</label><input id="fleet-lock-reason" required value="Initial dispatch assignment"></div><div class="form-actions field full"><button class="btn primary">Lock assignment at Dispatch</button></div></form><div id="fleet-lock-summary" class="notice" style="margin-top:14px;margin-bottom:0">No trip assignment is currently locked.</div></div><div class="panel" style="margin-top:14px"><div class="section-head"><div><div class="eyebrow">Immutable history</div><h2>Dispatch Audit Trail</h2></div><span class="tag gray" id="fleet-audit-count">0 events</span></div><div id="fleet-audit-list" class="empty">No dispatch events recorded.</div></div>`;
  document.querySelector('main')?.appendChild(section);
  const fleetTitle=['Drivers & Equipment.','Keep each driver, truck, and trailer as a separate reusable record.'];
  navButton.addEventListener('click',()=>{document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id==='fleet'));document.querySelectorAll('#nav button').forEach(b=>b.classList.toggle('active',b===navButton));document.getElementById('page-title').textContent=fleetTitle[0];document.getElementById('page-subtitle').textContent=fleetTitle[1];render();window.scrollTo({top:0,behavior:'smooth'});});
  const save=()=>localStorage.setItem(key,JSON.stringify(data));
  const esc=v=>String(v??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
  const uid=p=>p+'-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,6);
  const num=v=>String(v||'').trim()===''?null:Number(v);
  const item=(form,type)=>{const x=Object.fromEntries(new FormData(form).entries());x.id=uid(type);['gvwr','gcwr','emptyWeight'].forEach(k=>{if(k in x)x[k]=num(x[k])});return x};
  function driverEligibility(x){if(x?.status!=='active')return{label:'PLANNED',className:'orange',eligible:false};if(!x.licenseState||!x.expiration)return{label:'INCOMPLETE',className:'red',eligible:false};const expiration=new Date(x.expiration+'T23:59:59');if(Number.isNaN(expiration.getTime()))return{label:'INCOMPLETE',className:'red',eligible:false};if(expiration<new Date())return{label:'EXPIRED',className:'red',eligible:false};return{label:'VERIFIED',className:'',eligible:true}}
  function list(name,label,title,detail){const items=data[name],box=document.getElementById('fleet-'+label+'-list');document.getElementById('fleet-'+label+'-count').textContent=items.length;box.innerHTML=items.length?items.map(x=>{const driverState=label==='driver'?driverEligibility(x):null;const badge=driverState?.label||(x.status==='active'?'VERIFIED':'PLANNED');const badgeClass=driverState?.className||(x.status==='active'?'':'orange');const driverDetail=label==='driver'?(esc(x.qualification||'Qualification missing')+'<br>License: '+esc(x.licenseState||'missing')+' · Expires: '+esc(x.expiration?new Date(x.expiration+'T00:00:00').toLocaleDateString():'missing')):(esc(x[detail]||'Not verified')+(detail==='gvwr'&&x[detail]?' lb':''));return '<div class="metric-row"><span><strong>'+esc(x[title])+'</strong><br><small class="subtle">'+driverDetail+'</small></span><span class="tag '+badgeClass+'">'+badge+'</span></div>'}).join(''):'<div class="empty">No '+label+' records yet.</div>'}
  function opts(items,label){return '<option value="">Select '+label+'</option>'+items.map(x=>{const state=label==='driver'?driverEligibility(x):null;return '<option value="'+x.id+'">'+esc(x.name||x.unit)+' · '+(state?.label||(x.status==='active'?'Verified':'Planned'))+'</option>'}).join('')}
  function renderAudit(){const box=document.getElementById('fleet-audit-list');document.getElementById('fleet-audit-count').textContent=data.audit.length+' events';box.className='';box.innerHTML=data.audit.length?[...data.audit].reverse().map(x=>'<div class="metric-row"><span><strong>'+esc(x.action==='blocked_dispatch'?'DO NOT DISPATCH':(x.action==='authorized_change'?'AUTHORIZED CHANGE':'DISPATCH LOCK'))+'</strong><br><small class="subtle">'+esc(x.entityId)+' · '+new Date(x.timestamp).toLocaleString()+'<br>'+esc((x.reasons||[x.reason]).filter(Boolean).join(' · '))+'</small></span><span class="tag '+(x.action==='blocked_dispatch'?'red':'')+'">'+(x.action==='blocked_dispatch'?'BLOCKED':'RECORDED')+'</span></div>').join(''):'<div class="empty">No dispatch events recorded.</div>'}function render(){list('drivers','driver','name','qualification');list('trucks','truck','unit','gvwr');list('trailers','trailer','unit','gvwr');document.getElementById('fleet-lock-load').innerHTML='<option value="">Select load</option>'+store.loads.map(x=>'<option value="'+esc(x.id)+'">'+esc(x.id)+' · '+esc(x.customer)+'</option>').join('');document.getElementById('fleet-lock-driver').innerHTML=opts(data.drivers,'driver');document.getElementById('fleet-lock-truck').innerHTML=opts(data.trucks,'truck');document.getElementById('fleet-lock-trailer').innerHTML=opts(data.trailers,'trailer');const x=data.locks.at(-1);if(x){document.getElementById('fleet-lock-status').textContent='LOCKED';document.getElementById('fleet-lock-status').className='tag';document.getElementById('fleet-lock-summary').innerHTML='<strong>'+esc(x.loadId)+'</strong> locked to '+esc(x.driverName)+' · '+esc(x.truckUnit)+' · '+esc(x.trailerUnit)+'<br><span class="subtle">'+new Date(x.lockedAt).toLocaleString()+' · '+esc(x.reason)+'</span>'}renderAudit()}
  [['driver','drivers','DRV'],['truck','trucks','TRK'],['trailer','trailers','TRL']].forEach(([label,bucket,type])=>document.getElementById('fleet-'+label+'-form').addEventListener('submit',e=>{e.preventDefault();const record=item(e.currentTarget,type);data[bucket].push(record);save();render();e.currentTarget.reset();if(label==='driver'){const state=driverEligibility(record);toast(state.eligible?'Driver record saved and dispatch-eligible.':'Driver record saved as '+state.label+' / NOT DISPATCH-ELIGIBLE.')}else toast(label[0].toUpperCase()+label.slice(1)+' record saved.');}));
  document.getElementById('fleet-lock-form').addEventListener('submit',e=>{e.preventDefault();const loadId=document.getElementById('fleet-lock-load').value,d=data.drivers.find(x=>x.id===document.getElementById('fleet-lock-driver').value),t=data.trucks.find(x=>x.id===document.getElementById('fleet-lock-truck').value),r=data.trailers.find(x=>x.id===document.getElementById('fleet-lock-trailer').value),reason=document.getElementById('fleet-lock-reason').value.trim();const failures=[];if(!d)failures.push('A driver must be selected.');else{if(d.status!=='active')failures.push('Driver is not active and verified.');if(!d.licenseState)failures.push('Driver license state is missing.');if(!d.expiration)failures.push('Driver license expiration date is missing.');else{const expiration=new Date(d.expiration+'T23:59:59');if(Number.isNaN(expiration.getTime()))failures.push('Driver license expiration date is invalid.');else if(expiration<new Date())failures.push('Driver license expired on '+expiration.toLocaleDateString()+'.');}}if(t?.status!=='active'||!t.gvwr||!t.gcwr||!t.emptyWeight)failures.push('Truck verification or ratings are incomplete.');if(r?.status!=='active'||!r.gvwr||!r.emptyWeight)failures.push('Trailer verification or ratings are incomplete.');if(failures.length){data.audit.push({entity:'trip_lock',entityId:loadId||'No load selected',action:'blocked_dispatch',reasons:failures,timestamp:new Date().toISOString()});save();render();alert('DO NOT DISPATCH\n\n'+failures.join('\n'));return}const old=data.locks.find(x=>x.loadId===loadId);if(old&&!confirm('Authorized change only: continue and record the new assignment?'))return;const lock={id:uid('LOCK'),loadId,driverId:d.id,driverName:d.name,truckId:t.id,truckUnit:t.unit,trailerId:r.id,trailerUnit:r.unit,reason,lockedAt:new Date().toISOString()};data.locks.push(lock);data.audit.push({entity:'trip_lock',entityId:loadId,action:old?'authorized_change':'dispatch_lock',before:old||null,after:lock,reason,timestamp:lock.lockedAt});save();render();toast('Trip assignment locked and audit entry recorded.');});
  render();
})();