const assert=require('node:assert');
const fs=require('node:fs');
const vm=require('node:vm');
const elements=new Map(),element=(id='')=>({id,innerHTML:'',parentElement:null,addEventListener(){},querySelectorAll(){return[]},appendChild(child){child.parentElement=this;elements.set(child.id,child)},insertBefore(child){child.parentElement=this;elements.set(child.id,child)}});
const finance=element('finance'),close=element('v37-financial-close');close.parentElement=finance;elements.set(close.id,close);
const document={createElement:()=>element(),getElementById:id=>elements.get(id)||null,querySelector:selector=>selector==='#finance'?finance:null};
const load={id:'FLT-PAY-1',revenue:1000,invoice:{number:'INV-1',status:'Finalized',finalizedAt:'2026-09-08T00:00:00Z',total:1000},payments:[]};
const sandbox={document,window:{},current:()=>load,store:{loads:[load]},money:value=>'$'+value.toFixed(2),persist(){},toast(){},confirm:()=>true,Date};
vm.createContext(sandbox);vm.runInContext(fs.readFileSync('v37-payments-receivables.js','utf8'),sandbox);const api=sandbox.window.FLTPaymentsReceivables;
let result=api.recordPayment(load,{amount:400,date:'2026-09-08',method:'ACH',reference:'ABC'},{id:'PAY-1',now:new Date('2026-09-08T12:00:00Z')});
assert.equal(result.ok,true);assert.equal(result.payment.allocation.invoiceNumber,'INV-1');assert.equal(result.summary.status,'PARTIALLY PAID');assert.equal(result.summary.receivable,60000);
result=api.recordPayment(load,{amount:700,date:'2026-09-09',method:'Check',reference:'1001'},{id:'PAY-2'});assert.equal(result.summary.status,'OVERPAID');assert.equal(result.summary.receivable,-10000);
assert.equal(api.summary({...load,payments:[{id:'FULL',amount:1000,allocation:{invoiceNumber:'INV-1',amount:1000}}]}).status,'PAID');
const adjusted=api.summary({...load,payments:[{id:'FULL',amount:1000,allocation:{invoiceNumber:'INV-1',amount:1000}}],financialAdjustments:[{invoiceNumber:'INV-1',amount:-50}]});assert.equal(adjusted.receivable,-5000);assert.equal(adjusted.status,'OVERPAID');
result=api.reversePayment(load,'PAY-1','Wrong payment',{id:'REV-1',confirm:()=>true,date:'2026-09-10'});assert.equal(result.ok,true);assert.equal(result.reversal.amount,-400);assert.equal(result.summary.status,'PARTIALLY PAID');assert.equal(result.summary.receivable,30000);
assert.equal(api.reversePayment(load,'PAY-1','Again',{confirm:()=>true}).reason,'This payment has already been reversed.');
assert.equal(api.reversePayment(load,'PAY-2','Cancel',{confirm:()=>false}).reason,'Reversal cancelled.');
assert.equal(api.summary({...load,payments:[{id:'BAD',amount:10,allocation:{invoiceNumber:'OTHER',amount:10}}]}).allocationsMatch,false);
const legacy={id:'FLT-OLD',invoice:{number:'INV-OLD',status:'Finalized',total:50},payments:[{amount:25,date:'2026-01-01',method:'Cash'}]};assert.equal(api.normalizePayments(legacy),true);assert.ok(legacy.payments[0].id);assert.equal(legacy.payments[0].allocation.invoiceNumber,'INV-OLD');
const draftLoad={id:'FLT-DRAFT',invoice:{number:'INV-D',status:'Draft',total:100},payments:[]};assert.equal(api.recordPayment(draftLoad,{amount:100,date:'2026-09-08',method:'ACH'}).reason,'Finalize the invoice before recording payment.');
assert.match(elements.get('v37-payments-receivables').innerHTML,/payments & receivables/i);
console.log('V3.7 payment IDs, allocations, partial/paid/overpaid status, legacy migration, reversals, and render checks passed.');
