const assert=require('node:assert');const fs=require('node:fs');const vm=require('node:vm');
function el(id=''){return{id,innerHTML:'',textContent:'',className:'',style:{},value:'',listeners:{},parentElement:null,addEventListener(type,fn,capture){(this.listeners[type]||(this.listeners[type]=[])).push({fn,capture:Boolean(capture)})},insertAdjacentElement(position,child){child.parentElement=this.parentElement||this;elements.set(child.id,child)},closest(){return panelHost},appendChild(child){child.parentElement=this;elements.set(child.id,child)}}}
const elements=new Map(),panelHost=el('host'),form=el('fleet-lock-form'),loadSelect=el('fleet-lock-load'),driverSelect=el('fleet-lock-driver'),truckSelect=el('fleet-lock-truck'),trailerSelect=el('fleet-lock-trailer');form.parentElement=panelHost;[form,loadSelect,driverSelect,truckSelect,trailerSelect].forEach(x=>elements.set(x.id,x));
const document={createElement:()=>el(),getElementById:id=>elements.get(id)||null};const storage={};const localStorage={getItem:key=>storage[key]??null,setItem:(key,value)=>{storage[key]=String(value)}};
const load={id:'FLT-UI-W1',cargoWeight:6000,cargoLength:20,cargoWidth:8,transportationType:'General Freight'};const driver={id:'D1',status:'active',licenseState:'NC',expiration:'2027-09-08'},truck={id:'T1',status:'active',vin:'1FTFW1E50JFA00001',weightBasis:'scale-ticket',verificationDate:'2026-09-01',emptyWeight:8000,gvwr:14000,gcwr:30000,frontGawr:6000,rearGawr:9000,frontTireCapacity:6000,rearTireCapacity:9000,hitchCapacity:16000},trailer={id:'R1',status:'active',vin:'1UYVS2539P2000001',weightBasis:'scale-ticket',verificationDate:'2026-09-01',emptyWeight:5000,gvwr:14000,axleCapacity:14000,tireCapacity:14000,hitchCapacity:14000,deckLength:40,deckWidth:8.5,approvedTransportationTypes:['General Freight']};
localStorage.setItem('flt-v35-fleet',JSON.stringify({drivers:[driver],trucks:[truck],trailers:[trailer],locks:[],audit:[]}));localStorage.setItem('flt-v38-assignments',JSON.stringify({assignments:[{id:'ASN-1',loadId:load.id,driverId:'D1',truckId:'T1',trailerId:'R1',status:'Verified / Locked'}],assignmentAudit:[]}));loadSelect.value=load.id;driverSelect.value='D1';truckSelect.value='T1';trailerSelect.value='R1';let alerts=[],toasts=[];
const sandbox={window:{},document,localStorage,store:{loads:[load]},alert:value=>alerts.push(value),toast:value=>toasts.push(value),Date,globalThis:null};sandbox.globalThis=sandbox;vm.createContext(sandbox);vm.runInContext(fs.readFileSync('v38-assignment-integrity.js','utf8'),sandbox);vm.runInContext(fs.readFileSync('v38-weight-equipment-fit.js','utf8'),sandbox);vm.runInContext(fs.readFileSync('v38-weight-equipment-ui.js','utf8'),sandbox);const api=sandbox.window.FLTWeightEquipmentUI;
assert.equal(api.evaluate().status,'PASS');assert.match(elements.get('v38-weight-fit-panel').innerHTML,/Weight & Equipment Fit Gate/);assert.match(elements.get('v38-weight-fit-panel').innerHTML,/PASS/);
function submitEvent(){let prevented=false,stopped=false;const event={preventDefault(){prevented=true},stopImmediatePropagation(){stopped=true}};const handlers=(form.listeners.submit||[]).sort((a,b)=>Number(b.capture)-Number(a.capture));for(const {fn} of handlers){fn(event);if(stopped)break}return{prevented,stopped}}
let result=submitEvent();assert.equal(result.prevented,false);assert.equal(alerts.length,0);
load.cargoWeight=18000;result=submitEvent();assert.equal(result.prevented,true);assert.equal(result.stopped,true);assert.match(alerts.at(-1),/DO NOT DISPATCH/);assert.match(toasts.at(-1),/blocked this dispatch assignment/);let fleet=JSON.parse(localStorage.getItem('flt-v35-fleet'));assert.equal(fleet.audit.at(-1).action,'blocked_dispatch');assert.equal(fleet.audit.at(-1).entityId,load.id);assert.ok(fleet.audit.at(-1).reasons.some(x=>/payload|combination weight|GVWR/i.test(x)));
load.cargoWeight=6000;truck.verificationDate='';localStorage.setItem('flt-v35-fleet',JSON.stringify({...fleet,drivers:[driver],trucks:[truck],trailers:[trailer]}));alerts=[];result=submitEvent();assert.equal(result.prevented,true);assert.match(alerts.at(-1),/MORE INFORMATION REQUIRED/);fleet=JSON.parse(localStorage.getItem('flt-v35-fleet'));assert.ok(fleet.audit.at(-1).reasons.some(x=>/scale verification date/i.test(x)));
truck.verificationDate='2026-09-01';localStorage.setItem('flt-v35-fleet',JSON.stringify({...fleet,drivers:[driver],trucks:[truck],trailers:[trailer]}));load.transportationType='Auto Transport';alerts=[];result=submitEvent();assert.equal(result.prevented,true);assert.match(alerts.at(-1),/DO NOT DISPATCH/);assert.ok(JSON.parse(localStorage.getItem('flt-v35-fleet')).audit.at(-1).reasons.some(x=>/transportation type/i.test(x)));
load.transportationType='General Freight';alerts=[];result=submitEvent();assert.equal(result.prevented,false);assert.equal(alerts.length,0);console.log('V3.8 live Dispatch Weight & Equipment Fit Gate PASS, hard-stop, missing-data, audit, and transportation-type regression checks passed.');
