const assert=require('node:assert');const fs=require('node:fs');const vm=require('node:vm');
class El{constructor(id=''){this.id=id;this.value='';this.textContent='';this.innerHTML='';this.hidden=false;this.required=false;this.style={};this.dataset={};this.listeners={};this.children=[];this.parent=null;this.className='';}addEventListener(type,fn){(this.listeners[type]??=[]).push(fn)}dispatch(type,event={}){for(const fn of this.listeners[type]||[])fn({target:this,currentTarget:this,preventDefault(){},stopImmediatePropagation(){},...event})}insertAdjacentElement(where,child){child.parent=this.parent||this;elements.set(child.id,child)}insertBefore(child){child.parent=this;this.children.push(child);elements.set(child.id,child)}closest(){return panel}querySelector(selector){if(selector==='.form-actions')return actions;return null}focus(){}}
const elements=new Map(),form=new El('fleet-lock-form'),panel=new El('fleet-panel'),actions=new El('actions'),load=new El('fleet-lock-load'),driver=new El('fleet-lock-driver'),truck=new El('fleet-lock-truck'),trailer=new El('fleet-lock-trailer'),reason=new El('fleet-lock-reason'),detail=new El('fleet-lock-reason-detail'),detailField=new El('fleet-lock-reason-detail-field'),submit=new El('fleet-lock-submit');form.parent=panel;actions.parent=form;[form,load,driver,truck,trailer,reason,detail,detailField,submit].forEach(x=>elements.set(x.id,x));
const document={getElementById:id=>elements.get(id)||null,createElement:()=>new El(),};
const storage=new Map(),localStorage={getItem:key=>storage.has(key)?storage.get(key):null,setItem:(key,value)=>storage.set(key,String(value)),removeItem:key=>storage.delete(key)};
const fleet={drivers:[{id:'D1',name:'Driver One'},{id:'D2',name:'Driver Two'}],trucks:[{id:'T1',unit:'Truck 1'},{id:'T2',unit:'Truck 2'}],trailers:[{id:'R1',unit:'Trailer 1'}],locks:[{id:'LOCK-1',loadId:'FLT-UI-1',driverId:'D1',driverName:'Driver One',truckId:'T1',truckUnit:'Truck 1',trailerId:'R1',trailerUnit:'Trailer 1',reason:'Initial dispatch assignment',lockedAt:'2026-09-08T10:00:00Z'}],audit:[]};localStorage.setItem('flt-v35-fleet',JSON.stringify(fleet));load.value='FLT-UI-1';
let prompts=['Load cancelled'],confirms=[true],toasts=[];const sandbox={window:{},document,localStorage,Date,setTimeout:fn=>fn(),toast:value=>toasts.push(value),prompt:()=>prompts.shift(),confirm:()=>confirms.shift()??true,globalThis:null};sandbox.globalThis=sandbox;vm.createContext(sandbox);vm.runInContext(fs.readFileSync('v38-assignment-integrity.js','utf8'),sandbox);vm.runInContext(fs.readFileSync('v38-assignment-ui.js','utf8'),sandbox);const core=sandbox.window.FLTAssignmentIntegrity,ui=sandbox.window.FLTAssignmentUI;
let assignments=JSON.parse(localStorage.getItem('flt-v38-assignments'));assert.equal(assignments.assignments.length,1);assert.equal(assignments.assignments[0].loadId,'FLT-UI-1');assert.equal(assignments.assignments[0].truckId,'T1');assert.equal(assignments.assignmentAudit[0].type,'Assignment Migrated');assert.match(elements.get('v38-assignment-state').innerHTML,/VERIFIED \/ LOCKED/);assert.equal(elements.get('v38-cancel-assignment').hidden,false);
const changedFleet=JSON.parse(localStorage.getItem('flt-v35-fleet'));changedFleet.locks.push({id:'LOCK-2',loadId:'FLT-UI-1',driverId:'D1',driverName:'Driver One',truckId:'T2',truckUnit:'Truck 2',trailerId:'R1',trailerUnit:'Trailer 1',reason:'Truck unavailable',lockedAt:'2026-09-08T11:00:00Z'});localStorage.setItem('flt-v35-fleet',JSON.stringify(changedFleet));reason.value='Truck unavailable';ui.syncFromLegacy();assignments=JSON.parse(localStorage.getItem('flt-v38-assignments'));assert.equal(core.activeForLoad(assignments,'FLT-UI-1').truckId,'T2');assert.equal(assignments.assignments[0].status,'Superseded');assert.equal(assignments.assignmentAudit.at(-1).type,'Assignment Changed');assert.equal(assignments.assignmentAudit.at(-1).reason,'Truck unavailable');
ui.cancelCurrent();assignments=JSON.parse(localStorage.getItem('flt-v38-assignments'));assert.equal(core.activeForLoad(assignments,'FLT-UI-1'),null);assert.equal(assignments.assignmentAudit.at(-1).type,'Assignment Cancelled');const afterFleet=JSON.parse(localStorage.getItem('flt-v35-fleet'));assert.equal(afterFleet.locks.some(x=>x.loadId==='FLT-UI-1'),false);assert.equal(afterFleet.audit.at(-1).reason,'Load cancelled');assert.match(toasts.at(-1),/cancelled and preserved/);
console.log('V3.8 real Dispatch UI migration, Load-ID reassignment, supersession, and audited cancellation checks passed.');
