const assert=require('node:assert');const fs=require('node:fs');const vm=require('node:vm');
function el(id=''){return{id,innerHTML:'',textContent:'',className:'',style:{},value:'',files:null,listeners:{},parentElement:null,addEventListener(type,fn,capture){(this.listeners[type]||(this.listeners[type]=[])).push({fn,capture:Boolean(capture)})},appendChild(child){child.parentElement=this;elements.set(child.id,child)},querySelector(){return grid},closest(){return this}}}
const elements=new Map(),pickup=el('pickup'),delivery=el('delivery'),pickupGrid=el('pickup-grid'),deliveryGrid=el('delivery-grid'),pickupStatus=el('pickup-status'),deliveryStatus=el('delivery-status'),savePickup=el('save-pickup'),saveDelivery=el('save-delivery'),pod=el('download-pod');const grid=pickupGrid;pickup.querySelector=()=>pickupGrid;delivery.querySelector=()=>deliveryGrid;[pickup,delivery,pickupStatus,deliveryStatus,savePickup,saveDelivery,pod].forEach(x=>elements.set(x.id,x));
const document={createElement:()=>el(),getElementById:id=>elements.get(id)||null};let persisted=0,alerts=[],toasts=[];
const load={id:'FLT-UI-PD1',transportationType:'General Freight',documents:[],pickupProof:{name:'Shipper',time:'08:00',signature:'pickup-sig'},deliveryProof:{name:'Receiver',time:'15:00',signature:'delivery-sig'}};
const sandbox={window:{},document,current:()=>load,store:{selectedId:load.id,loads:[load]},persist(){persisted++},localStorage:{setItem(){}},toast:value=>toasts.push(value),alert:value=>alerts.push(value),setTimeout:fn=>fn(),Date,globalThis:null};sandbox.globalThis=sandbox;vm.createContext(sandbox);vm.runInContext(fs.readFileSync('v38-document-compliance.js','utf8'),sandbox);vm.runInContext(fs.readFileSync('v38-pickup-delivery-integrity.js','utf8'),sandbox);vm.runInContext(fs.readFileSync('v38-pickup-delivery-ui.js','utf8'),sandbox);const api=sandbox.window.FLTPickupDeliveryUI;
let state=api.refresh();assert.equal(state.pickup.pass,false);assert.equal(state.delivery.pass,false);assert.equal(pickupStatus.textContent,'Incomplete');assert.equal(deliveryStatus.textContent,'Incomplete');assert.match(elements.get('v38-pickup-integrity').innerHTML,/Pickup Document Integrity/);assert.match(elements.get('v38-delivery-integrity').innerHTML,/Delivery Document Integrity/);
function fire(target,type,event={}){for(const {fn} of target.listeners[type]||[])fn(event)}
let prevented=false,stopped=false;fire(pod,'click',{preventDefault(){prevented=true},stopImmediatePropagation(){stopped=true}});assert.equal(prevented,true);assert.equal(stopped,true);assert.match(alerts.at(-1),/POD NOT READY/);assert.match(toasts.at(-1),/Delivery Document Integrity/);
load.documents.push({id:'DOC-P1',loadId:load.id,stage:'pickup',type:'Bill of Lading / Shipping Document',filename:'bol.pdf',status:'Attached'});fire(savePickup,'click');state=api.refresh();assert.equal(state.pickup.pass,true);assert.equal(pickupStatus.textContent,'Complete');assert.equal(state.delivery.pass,false);
load.documents.push({id:'DOC-D1',loadId:load.id,stage:'delivery',type:'Proof of Delivery',filename:'pod.pdf',status:'Attached'});fire(saveDelivery,'click');state=api.refresh();assert.equal(state.delivery.pass,true);assert.equal(deliveryStatus.textContent,'Complete');alerts=[];prevented=false;stopped=false;fire(pod,'click',{preventDefault(){prevented=true},stopImmediatePropagation(){stopped=true}});assert.equal(prevented,false);assert.equal(stopped,false);assert.equal(alerts.length,0);
load.documents.push({id:'DOC-X',loadId:'OTHER-LOAD',stage:'delivery',type:'Proof of Delivery',filename:'wrong-load.pdf',status:'Attached'});state=api.refresh();assert.equal(state.delivery.pass,true);assert.ok(!elements.get('v38-delivery-integrity').innerHTML.includes('wrong-load.pdf'));
assert.ok(persisted>=0);console.log('V3.8 live Pickup/Delivery integrity UI status, Load-ID evidence isolation, and POD blocking checks passed.');
