const assert=require('assert');
const fs=require('fs');
const vm=require('vm');
const context={window:{}};
vm.createContext(context);
vm.runInContext(fs.readFileSync('v38-acceptance-gate.js','utf8'),context);
const gate=context.window.FLTV38AcceptanceGate;
const pass={pass:true,status:'PASS'};
const good=gate.evaluate({assignment:pass,weightEquipment:pass,documentCompliance:pass,pickupDelivery:pass,autoPopulate:pass,legacyV35:true,legacyV36:true,legacyV37:true});
assert.strictEqual(good.pass,true);
assert.strictEqual(good.status,'PASS');
assert.deepStrictEqual(Array.from(good.failed),[]);
const blocked=gate.evaluate({assignment:pass,weightEquipment:{pass:false,status:'DO NOT DISPATCH'},documentCompliance:pass,pickupDelivery:pass,autoPopulate:pass,legacyV35:true,legacyV36:true,legacyV37:true});
assert.strictEqual(blocked.pass,false);
assert.strictEqual(blocked.status,'BLOCKED');
assert.strictEqual(blocked.failed.includes('weightEquipment'),true);
const regression=gate.evaluate({assignment:pass,weightEquipment:pass,documentCompliance:pass,pickupDelivery:pass,autoPopulate:pass,legacyV35:true,legacyV36:true,legacyV37:false});
assert.strictEqual(regression.pass,false);
assert.strictEqual(regression.failed.includes('legacyV37'),true);
console.log('V3.8 Acceptance Gate milestone and legacy-regression blocking checks passed.');
