const assert=require('node:assert');const fs=require('node:fs');const vm=require('node:vm');const sandbox={window:{},Date};vm.createContext(sandbox);vm.runInContext(fs.readFileSync('v38-weight-equipment-fit.js','utf8'),sandbox);const api=sandbox.window.FLTWeightEquipmentFit;
const driver={id:'D1',status:'active',licenseState:'NC',expiration:'2027-09-08'},truck={id:'T1',status:'active',vin:'1FTFW1E50JFA00001',weightBasis:'scale-ticket',verificationDate:'2026-09-01',emptyWeight:8000,gvwr:14000,gcwr:30000,frontGawr:6000,rearGawr:9000,frontTireCapacity:6000,rearTireCapacity:9000,hitchCapacity:16000},trailer={id:'R1',status:'active',vin:'1UYVS2539P2000001',weightBasis:'scale-ticket',verificationDate:'2026-09-01',emptyWeight:5000,gvwr:14000,axleCapacity:14000,tireCapacity:14000,hitchCapacity:14000,deckLength:40,deckWidth:8.5,approvedTransportationTypes:['General Freight']},assignment={loadId:'FLT-38-W1',driverId:'D1',truckId:'T1',trailerId:'R1',status:'Verified / Locked'};
let result=api.evaluate({load:{id:'FLT-38-W1',cargoWeight:6000,cargoLength:20,cargoWidth:8,transportationType:'General Freight'},assignment,driver,truck,trailer});assert.equal(result.status,'PASS');assert.equal(result.pass,true);assert.equal(result.metrics.estimatedCombinationWeight,19000);assert.equal(result.metrics.estimatedPayloadAvailable,15000);
result=api.evaluate({load:{id:'FLT-38-W1',cargoWeight:18000,transportationType:'General Freight'},assignment,driver,truck,trailer});assert.equal(result.status,'DO NOT DISPATCH');assert.ok(result.hardStops.some(x=>/payload|combination weight|GVWR/i.test(x)));
result=api.evaluate({load:{id:'FLT-38-W1',cargoWeight:6000,cargoLength:45,transportationType:'General Freight'},assignment,driver,truck,trailer});assert.equal(result.status,'DO NOT DISPATCH');assert.ok(result.hardStops.some(x=>/deck length/i.test(x)));
result=api.evaluate({load:{id:'FLT-38-W1',cargoWeight:6000,transportationType:'Auto Transport'},assignment,driver,truck,trailer});assert.equal(result.status,'DO NOT DISPATCH');assert.ok(result.hardStops.some(x=>/transportation type/i.test(x)));
result=api.evaluate({load:{id:'FLT-38-W1',cargoWeight:6000},assignment:null,driver,truck:{...truck,verificationDate:''},trailer});assert.equal(result.status,'MORE INFORMATION REQUIRED');assert.ok(result.missing.some(x=>/verified.*assignment/i.test(x)));assert.ok(result.missing.some(x=>/scale verification date/i.test(x)));
result=api.evaluate({load:{id:'FLT-38-W1',cargoWeight:6000},assignment,driver,truck:{...truck,frontTireCapacity:5000},trailer});assert.equal(result.status,'DO NOT DISPATCH');assert.ok(result.hardStops.some(x=>/front-axle tire/i.test(x)));
console.log('V3.8 Weight & Equipment Fit Gate PASS, missing-data, payload, dimensional-fit, transportation-type, and hard-stop checks passed.');
